export default [
  {
    workOrderid: "1",
    userId: "1",
    userName: "Joel Smith",
    userEmail: "joel@joel.com",
    userPhone: "470-345-6190",
    userAptNumber: "211",
    category: "Apartment",
    description: "AC stopped working",
  },
  {
    workOrderid: "2",
    userId: "2",
    userName: "Ellen Kramp",
    userEmail: "ellen@kramp.com",
    userPhone: "770-375-5846",
    userAptNumber: "413",
    category: "Common Area",
    description: "Parking garage light on level 3 is out",
  },
  {
    workOrderid: "3",
    userId: "1",
    userName: "Joel Smith",
    userEmail: "joel@joel.com",
    userPhone: "470-345-6190",
    userAptNumber: "211",
    category: "Common Area",
    description: "Stain on carpet in front of elevator 2",
  },
  {
    workOrderid: "4",
    userId: "2",
    userName: "Ellen Kramp",
    userEmail: "ellen@kramp.com",
    userPhone: "770-375-5846",
    userAptNumber: "413",
    category: "Apartment",
    description: "The power in my living room goes out everytime I use the vacuum",
  },
  {
    workOrderid: "5",
    userId: "1",
    userName: "Joel Smith",
    userEmail: "joel@joel.com",
    userPhone: "470-345-6190",
    userAptNumber: "211",
    category: "Apartment",
    description: "The shower won't turn off all the way",
  },
  {
    workOrderid: "6",
    userId: "2",
    userName: "Ellen Kramp",
    userEmail: "ellen@kramp.com",
    userPhone: "770-375-5846",
    userAptNumber: "413",
    category: "Common Area",
    description: "A dog peed in elevator #3",
  }
]
