const initialState =  {
    requests: [
        {title: 'Clean up bathroom', 
            description: 'Lorem ipsum dolor sit amet, nihil tollit euismod quo ea, nec qualisque pertinacia ea. Cu quot vituperata vim. Cu hinc homero noster cum, error dolore timeam eu his. Eum eu iudico laudem.',
            status: 'complete',
            id: '567',
            userId: '',
        },
        {title: 'Replace hallway bulb',
            description: 'Lorem ipsum dolor sit amet, nihil tollit euismod quo ea, nec qualisque pertinacia ea. Cu quot vituperata vim. Cu hinc homero noster cum, error dolore timeam eu his. Eum eu iudico laudem.',
            status: 'in progress',
            id: '457',
            userId: '',
        },
        {title: 'Mail box is broken',
            description: 'Cu quot vituperata vim. Cu hinc homero noster cum, error dolore timeam eu his. Eum eu iudico laudem.',
            status: 'canceled',
            id: '173',
            userId: '',
        },
        {title: 'Busted lock on pool gate',
            description: 'Ius te suas primis, ei summo repudiare intellegat est. Elitr munere bonorum mel ad.',
            status: 'complete',
            id: '190',
            userId: '',
        },
        {title: 'AC unit is broken',
            description: 'Et feugiat civibus eos. Ut definiebas dissentias cum, nam te semper copiosae postulant. Dolore omnesque vix eu, malorum inermis denique ad eam.',
            status: 'in progress',
            id: '753',
            userId: '',
        },
        {title: 'Flooding kitchen sink',
            description: 'Et feugiat civibus eos. Ut definiebas dissentias cum, nam te semper copiosae postulant. Dolore omnesque vix eu, malorum inermis denique ad eam.',
            status: 'in progress',
            id: '136',
            userId: '',
        },
        {title: 'Noisy Neighbors above',
            description: 'Et feugiat civibus eos. Ut definiebas dissentias cum, nam te semper copiosae postulant. Dolore omnesque vix eu, malorum inermis denique ad eam.',
            status: 'Completed',
            id: '345',
            userId: '',
        },
        {title: 'Boxes blocking parking tower exit',
            description: 'Et feugiat civibus eos. Ut definiebas dissentias cum, nam te semper copiosae postulant. Dolore omnesque vix eu, malorum inermis denique ad eam.',
            status: 'Completed',
            id: '583',
            userId: '',
        },
        {title: 'Graffiti on shed wall',
            description: 'Et feugiat civibus eos. Ut definiebas dissentias cum, nam te semper copiosae postulant. Dolore omnesque vix eu, malorum inermis denique ad eam.',
            status: 'in progress',
            id: '193',
            userId: '',
        },
        {title: "Trash wasn't collected at last date",
            description: 'Et feugiat civibus eos. Ut definiebas dissentias cum, nam te semper copiosae postulant. Dolore omnesque vix eu, malorum inermis denique ad eam.',
            status: 'in progress',
            id: '426',
            userId: '',
        },
    ]
}

export default initialState;